apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acme-diff-preview.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acme-diff-preview.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
